### ISSUE TITLE
Automatically split up SQL queries when query gets too complex

### ISSUE THREAD

**Issue by scholtzan** [mozilla/opmon#1]
If a large number of probes need to be considered for a project, then the SQL query can become too complex erroring out with `Resources exceeded`. In those cases we should split up the query and save the results in temporary tables that subsequently get `UNION`ed.

There are several possible approaches:
1. fixed threshold for number of probes per query
2. run query and split up if we see the error, try again until all queries are running successfully

**Comment by jklukas** [comment]
Do you have a good sense of what's contributing to the complexity? Generally it's some combination of UDF calls and subqueries. There are a few tricks in [clients_daily_v6](https://github.com/mozilla/bigquery-etl/blob/main/sql/moz-fx-data-shared-prod/telemetry_derived/clients_daily_v6/query.sql) used to batch similar transformations together in arrays so that we can have a single UDF invocation serve multiple probes. Do you think any of those ideas could be applied here to avoid splitting to multiple queries?

**Comment by scholtzan** [comment]
I've seen this happen with 40+ probes. I think it's due to calling `mozfun.hist.extract` on most of them. It's definitely worth taking a look at clients_daily for this 👍

**Comment by relud** [comment]
this needs to support at least 400 probes configured, so while solving this may include the array trick to reduce udf calls, it may also require splitting queries to reach that scale.

**Comment by scholtzan** [comment]
This has been implemented
